# hyperparameters.yaml

num_train_epochs: 5
per_device_train_batch_size: 32
per_device_eval_batch_size: 32
learning_rate: 2e-5
evaluation_strategy: 'epoch'
eval_steps: 0
save_strategy: 'epoch'
save_steps: 0
logging_steps: 500
save_total_limit: 2
load_best_model_at_end: True
metric_for_best_model: 'eval_loss'
greater_is_better: False
semantic_weight: 0.5
hidden_weight: 0.5
bf16: True
fp16: False
gradient_accumulation_steps: 1
gradient_checkpointing: False
eval_accumulation_steps: 1
early_stopping_patience: 10
temperature: 2.0